version: '3.8'

services:
  breaking-news-srv:
    image: 10.20.64.25:5000/breaking-news-srv:latest
    environment:
      - TZ=Asia/Dubai
      - PORT=5000
    ports:
      - "5001:5000"
    build:
      context: .
      dockerfile: ./Dockerfile
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.http.routers.breaking-news-srv.rule=Host:traefik.corp.asharq.net
        - traefik.http.services.breaking-news-srv.loadbalancer.server.port=5001
